#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS+=$(IDF_PATH)/../pluto
EXTRA_COMPONENT_DIRS+=$(IDF_PATH)/../pluto_stack

PROJECT_NAME := PL-Switch3-A01
include $(IDF_PATH)/make/project.mk


